language: java
jdk:
- openjdk8
- oraclejdk8

sudo: false

env:
  global:
  - BUILD_CMD='make'
  - RUN_TESTS=false
  
matrix:
  include:
  - jdk: oraclejdk8
    env:
    - BUILD_CMD='mvn -DEMBOSS_ROOT=$EMBOSS_ROOT'
    - RUN_TESTS=true
    
cache:
  directories:
  - "${HOME}/.m2"
  - "${HOME}/dependencies"
  
before_install:
- openssl aes-256-cbc -K $encrypted_63c9cb0d86e4_key -iv $encrypted_63c9cb0d86e4_iv
  -in artemis_keystore.jks.enc -out artemis_keystore.jks -d
- export CASHER_TIME_OUT=300
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- source install_dependencies.sh

install:
  - "$BUILD_CMD"

script:
- if [ "$RUN_TESTS" == "true" ]; then cd test; ln -s $(pwd)/../etc/log4j.properties
  .; ./RunDefaultUnitTests.sh | tee test.log && [ -z "$(grep 'Failures:\s[^0]\|Errors:\s[^0]'
  test.log)" ]; fi

deploy:
  provider: releases
  api_key: "ec10fb88273b7582110c46d4f42d352e1ca70ff0"
  file_glob: true
  file: $TRAVIS_BUILD_DIR/target/release-artifacts/*
  skip_cleanup: true
  target_commitish: tmp-release-test
  name: $TRAVIS_TAG
  body: “Automated Travis CI build. Please see release notes for details.”
  draft: true
  prerelease: false 
  on:
    branch: tmp-release-test
    jdk: oraclejdk8
    tags: true
    
after_success:
  - rm -f $TRAVIS_BUILD_DIR/artemis_keystore.jks
  
 after_failure:
  - rm -f $TRAVIS_BUILD_DIR/artemis_keystore.jks
  
  