language: java
jdk:
  - openjdk8
  - oraclejdk8
sudo: true
matrix:
  include:
    - jdk: oraclejdk8
      env: 
       - BUILD_CMD='mvn -Dskip.tests=true clean package'
       - RUN_TESTS=true
       - EVOSUITE_TEST_EXCLUDES=**/artemis/*ESTest.*
    - jdk: openjdk8
      env: 
       - BUILD_CMD='mvn -Dskip.tests=true clean package'
       - RUN_TESTS=true
       - EVOSUITE_TEST_EXCLUDES=**/artemis/**/*ESTest.*
cache:
  directories:
  - "${HOME}/dependencies"
before_install:
  - "export CASHER_TIME_OUT=300"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "source install_dependencies.sh"
  - mvn validate
install:
  - "$BUILD_CMD"
script:
  - if [ "$RUN_TESTS" == "true" ]; then
      cd test;
      ln -s $(pwd)/../etc/log4j.properties .;
      ./RunTravisTests.sh -e $EVOSUITE_TEST_EXCLUDES | tee test.log && [ -z "$(grep 'Failures:\s[^0]\|Errors:\s[^0]' test.log)" ];
    fi