language: java
jdk:
  - openjdk7
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "make"
  - "cd test"
script: ant -f build-test.xml test | tee test.log && [ -z "$(grep 'Failures:\s[^0]\|Errors:\s[^0]' test.log)" ]
