language: java
jdk:
  - oraclejdk8
sudo: true
env:
  global:
    - BUILD_CMD='mvn -X -Dskip.tests=true validate clean install'
    - RUN_TESTS=false
matrix:
  include:
  - jdk: oraclejdk8
    env:
    - RUN_TESTS=false
cache:
  directories:
  - "${HOME}/dependencies"
before_install:
  - "export CASHER_TIME_OUT=300"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "source install_dependencies.sh"
  - mvn -X validate"
install:
  - "$BUILD_CMD"
script:
  - if [ "$RUN_TESTS" == "true" ]; then
      cd test;
      ln -s $(pwd)/../etc/log4j.properties .;
      ./RunAllUnitTests.sh | tee test.log && [ -z "$(grep 'Failures:\s[^0]\|Errors:\s[^0]' test.log)" ];
    fi